'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_REGISTER_RESTRICTIONS_TBL
    Public Property REGISTER As String
    Public Property ID_ORDER As Nullable(Of Integer)
    Public Property VAL As String
    Public Property VAL2 As String

End Class
