'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_SUBS_PHONES_TBL
    Public Property TRC_PHONE_ID As Long
    Public Property TRC_PHONE_COMMENT As String
    Public Property TRC_TSTAMP As Nullable(Of Decimal)
    Public Property TRC_RR_JOURNAL As Nullable(Of Byte)
    Public Property SUBSCRIBER_ID As Nullable(Of Long)
    Public Property SUBSCRIBER_PHONE_ID As Nullable(Of Long)
    Public Property PHONE_NUMBER As String
    Public Property VALID As Nullable(Of Integer)
    Public Property MAIN_PHONE As Nullable(Of Integer)
    Public Property FV_ORIGIN As Nullable(Of Long)
    Public Property CREATION_DATE As Date
    Public Property LAST_UPDATE_DATE As Nullable(Of Date)

End Class
