'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_CE_DOCUMENTS_TBL
    Public Property TRC_DOCUMENT_ID As Long
    Public Property TRC_GPS_LAT As String
    Public Property TRC_GPS_LNG As String
    Public Property TRC_TSTAMP As Nullable(Of Decimal)
    Public Property TRC_RR_JOURNAL As Nullable(Of Byte)
    Public Property TRC_RR_DOCUMENT_KIND As Nullable(Of Byte)
    Public Property CE_DOCUMENT_ID As Nullable(Of Long)
    Public Property ACCOUNT_ID As Nullable(Of Long)
    Public Property CREATION_DATE As Nullable(Of Date)
    Public Property DOCUMENT_DESCRIPTION As String
    Public Property DOCUMENT_LINK As String

End Class
