'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_SUBS_CONTACTS_EML_TBL
    Public Property TRC_EMAIL_ID As Long
    Public Property TRC_EMAIL_COMMENT As String
    Public Property TRC_TSTAMP As Nullable(Of Decimal)
    Public Property TRC_RR_JOURNAL As Nullable(Of Byte)
    Public Property SUBSCRIBER_ID As Nullable(Of Long)
    Public Property SUBSCRIBER_CONTACT_ID As Nullable(Of Long)
    Public Property EMAIL As String
    Public Property EMAIL_FLAG As Nullable(Of Integer)
    Public Property FV_ORIGIN As Nullable(Of Integer)
    Public Property CREATION_DATE As Date
    Public Property LAST_UPDATE_DATE As Nullable(Of Date)

End Class
