'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_SUBS_CONTACTS_EMP_TBL
    Public Property TRC_EMPLOYER_ID As Long
    Public Property TRC_TSTAMP As Nullable(Of Decimal)
    Public Property TRC_RR_JOURNAL As Nullable(Of Byte)
    Public Property SUBSCRIBER_ID As Nullable(Of Long)
    Public Property SUBSCRIBER_CONTACT_ID As Nullable(Of Long)
    Public Property LAST_NAME As String
    Public Property CITY As String
    Public Property STREET_NUMBER As String
    Public Property STREET As String
    Public Property POSTAL_CODE As String
    Public Property EMAIL As String
    Public Property PHONE1 As String
    Public Property ADDRESS_FULL As String
    Public Property FV_ORIGIN As Nullable(Of Integer)
    Public Property VALID As Nullable(Of Integer)
    Public Property CREATION_DATE As Date
    Public Property LAST_UPDATE_DATE As Nullable(Of Date)

End Class
