'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGCZ_PAYMENTS_TBL
    Public Property TRC_PAYMENT_ID As Long
    Public Property TRC_TSTAMP As Nullable(Of Decimal)
    Public Property TRC_RR_JOURNAL As Nullable(Of Byte)
    Public Property ACCOUNT_ID As Nullable(Of Long)
    Public Property PAYMENT_ID As Nullable(Of Long)
    Public Property PAYMENT_DATE As Nullable(Of Date)
    Public Property AMOUNT As Nullable(Of Decimal)
    Public Property BEFORE_FV_FLAG As Nullable(Of Boolean)
    Public Property SOLD As Nullable(Of Decimal)

End Class
