'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_ACCOUNTS_VW
    Public Property ACCOUNT_ID As Long
    Public Property FIELD_VISIT_OUT_ID As Long
    Public Property IDUSR As Long
    Public Property TOTAL_BALANCE As Nullable(Of Decimal)
    Public Property TAKE_OVER_DATE As Nullable(Of Date)
    Public Property CLIENT_ID As Nullable(Of Long)
    Public Property DEBT_BALANCE_SUM As Nullable(Of Decimal)
    Public Property INTEREST_BALANCE_SUM As Nullable(Of Decimal)
    Public Property COST_BALANCE_SUM As Nullable(Of Decimal)
    Public Property PAYMENTS_AMOUNT_SUM As Nullable(Of Decimal)
    Public Property PRODUCT_NUMBER As String
    Public Property BANK_ACCOUNT_NUM As String
    Public Property BANK_CODE As String
    Public Property VARIABLE_SYMBOL As String
    Public Property SPECIFIC_SYMBOL As String
    Public Property LAST_PAYMENT_DATE As Nullable(Of Date)
    Public Property LAST_PAYMENT_AMOUNT As Nullable(Of Decimal)
    Public Property LAST_CALL_DATE As Nullable(Of Date)
    Public Property LAST_CALL_TEXT As String
    Public Property LAST_INSTRUCTION_FOR_FV As String
    Public Property CAMPAIGN As String
    Public Property FV_PASSING_ON_DATE As Date
    Public Property FV_TERMINATION_DATE As Nullable(Of Date)
    Public Property FIRST_FV_DEADLINE_DAYS As Nullable(Of Byte)
    Public Property NEXT_FV_DEADLINE_DAYS As Nullable(Of Byte)
    Public Property PA_INSTALMENT_BREAK_DATE_FV As Nullable(Of Date)
    Public Property CE_RETURN_DATE As Nullable(Of Date)
    Public Property LAPSE_DATE As Nullable(Of Date)
    Public Property PAYMENTS_AMOUNT_FV As Nullable(Of Decimal)
    Public Property PA_STATUS_FV As String
    Public Property PA_TYPE_ID_FV As Nullable(Of Decimal)
    Public Property PA_COUNT As Nullable(Of Decimal)
    Public Property CE_DEBT_REMISSION_STATUS As String
    Public Property PA_MAX_PERIODS As Nullable(Of Decimal)
    Public Property DOHL As String
    Public Property PROBIHAJICI_AKCE As String
    Public Property COMMISSION As Nullable(Of Decimal)

End Class
