'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_ACCOUNT_DEBTS_VW
    Public Property ACCOUNT_DEBT_ID As Long
    Public Property ACCOUNT_ID As Nullable(Of Long)
    Public Property DEBT_SUBCLASS_NAME As String
    Public Property INVOICE_NUMBER As String
    Public Property DEBT_AMOUNT As Nullable(Of Decimal)
    Public Property DEBT_BALANCE As Nullable(Of Decimal)
    Public Property DEBT_BALANCE_UPDATE As Nullable(Of Decimal)
    Public Property DEBT_DATE As Nullable(Of Date)
    Public Property DEBT_DUE_DATE As Nullable(Of Date)
    Public Property CURRENCY As String

End Class
