'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_ACC_SUBS_INT_VW
    Public Property ACCOUNT_ID As Long
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_TYPE_ID As Long
    Public Property MAIN As Nullable(Of Boolean)
    Public Property DEBT_ACCEPT_DATE As Nullable(Of Date)

End Class
