'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_CE_DOCUMENTS_VW
    Public Property ACCOUNT_ID As Long
    Public Property CE_DOCUMENT_ID As Long
    Public Property CREATION_DATE As Nullable(Of Date)
    Public Property DOCUMENT_DESCRIPTION As String
    Public Property DOCUMENT_LINK As String

End Class
