'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_CLIENTS_VW
    Public Property CLIENT_ID As Long
    Public Property ACCOUNT_ID As Long
    Public Property NAME As String
    Public Property NAME_ALIAS As String
    Public Property ADDRESS As String

End Class
