'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_FIELD_VISIT_OUT
    Public Property FIELD_VISIT_OUT_ID As Long
    Public Property ACCOUNT_ID As Long
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_ADDRESS_ID As Long
    Public Property FIELD_VISIT_POST_CODE_ID As Long
    Public Property IDUSR As Long
    Public Property DEBT_BALANCE As Decimal
    Public Property PASSING_ON_DATE As Date
    Public Property TAKE_OVER_DATE As Nullable(Of Date)
    Public Property REJECTION_DATE As Nullable(Of Date)
    Public Property REJECTION_REASON As String
    Public Property TERMINATION_DATE As Date
    Public Property TERMINATION_REASON As String

End Class
