'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_PA_INSTALLMENTS_VW
    Public Property ACCOUNT_ID As Long
    Public Property PA_INSTALLMENT_ID As Integer
    Public Property DUE_DATE As Date
    Public Property AMOUNT_INSTALLMENT As Nullable(Of Decimal)
    Public Property UNPAID_AMOUNT_INSTALLMENT As Nullable(Of Decimal)

End Class
