'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_PRINT_ADD_INFO_CEZ_VW
    Public Property ACCOUNT_ID As Long
    Public Property ODBERNE_MISTO As String
    Public Property VARIABILNI_SYMBOL As String
    Public Property DATUM_SPLATNOSTI As Nullable(Of Date)
    Public Property FAKTUROVANA_CASTKA As Nullable(Of Decimal)
    Public Property VYSE_DOPLATKU As Nullable(Of Decimal)

End Class
