'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_PRINT_ADD_INFO_VW
    Public Property ACCOUNT_ID As Long
    Public Property CUSTOMER_ID As String
    Public Property CUSTOMER_ID_SECOND As String
    Public Property REGISTER_INFO As String
    Public Property ACC_COMMENT9 As String
    Public Property ACC_COMMENT13 As String
    Public Property ACC_COMMENT14 As String
    Public Property ACC_COMMENT17 As String
    Public Property ACC_COMMENT23 As String
    Public Property ACC_COMMENT27 As String
    Public Property PF_SMLOUVY As String
    Public Property SLOVY_TO As String
    Public Property SLOVY_TO_HAL As String

End Class
