'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_PA_INSTALLMENT_HISTORY_VW
    Public Property ACCOUNT_ID As Long
    Public Property PA_INSTANCE_ID As Integer
    Public Property CREATION_DATE As Nullable(Of Date)
    Public Property AMOUNT_PA As Nullable(Of Decimal)
    Public Property PA_INSTALLMENTS_COUNT As Nullable(Of Decimal)
    Public Property STAUS As String
    Public Property PA_TYPE_ID As Integer

End Class
