'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_PAYMENTS_VW
    Public Property ACCOUNT_ID As Long
    Public Property PAYMENT_ID As Long
    Public Property PAYMENT_DATE As Nullable(Of Date)
    Public Property AMOUNT As Nullable(Of Decimal)
    Public Property BEFORE_FV_FLAG As Nullable(Of Decimal)
    Public Property SOLD As Nullable(Of Decimal)

End Class
