'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_SUBSCRIBER_CONTACTS_EMP_VW
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_CONTACT_ID As Long
    Public Property LAST_NAME As String
    Public Property CITY As String
    Public Property STREET As String
    Public Property POSTAL_CODE As String
    Public Property EMAIL As String
    Public Property PHONE1 As String
    Public Property ADDRESS_FULL As String
    Public Property FV_ORIGIN As Nullable(Of Decimal)
    Public Property VALID As Nullable(Of Decimal)

End Class
