'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_SUBSCRIBER_PHONES_VW
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_PHONE_ID As Long
    Public Property PHONE_NUMBER As String
    Public Property VALID As Nullable(Of Byte)
    Public Property MAIN_PHONE As Nullable(Of Boolean)
    Public Property FV_ORIGIN As Nullable(Of Decimal)

End Class
