'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_SUBSCRIBER_ADDRESSES_VW
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_ADDRESS_ID As Long
    Public Property CITY As String
    Public Property STREET_NUMBER As String
    Public Property STREET As String
    Public Property POSTAL_CODE As String
    Public Property PERS_REGION As String
    Public Property MAIN_ADDRESS As Nullable(Of Boolean)
    Public Property VALID As Nullable(Of Boolean)
    Public Property ADDRESS_TYPE As Long
    Public Property FV_ORIGIN As Nullable(Of Decimal)

End Class
