'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_SUBSCRIBER_CONTACTS_EML_VW
    Public Property SUBSCRIBER_ID As Long
    Public Property SUBSCRIBER_CONTACT_ID As Long
    Public Property EMAIL As String
    Public Property EMAIL_FLAG As Nullable(Of Decimal)
    Public Property FV_ORIGIN As Nullable(Of Decimal)

End Class
