'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CZ_SUBSCRIBERS_VW
    Public Property SUBSCRIBER_ID As Long
    Public Property LAST_NAME As String
    Public Property FIRST_NAME As String
    Public Property SSN As String
    Public Property J_ATTRIBUTE As String
    Public Property BIRTH_DATE As Nullable(Of Date)
    Public Property LAST_NAME2 As String
    Public Property BONITA_KATASTR As String
    Public Property BONITA_POCET_EXE As Nullable(Of Byte)
    Public Property BONITA_DATUM_LUSTRACE As Nullable(Of Date)

End Class
