'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class SqlEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SqlEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblCashPayments() As DbSet(Of tblCashPayment)
    Public Overridable Property tblCreditors() As DbSet(Of tblCreditor)
    Public Overridable Property tblErrors() As DbSet(Of tblError)
    Public Overridable Property tblLogServices() As DbSet(Of tblLogService)
    Public Overridable Property tblOtherInfoes() As DbSet(Of tblOtherInfo)
    Public Overridable Property tblRegisterRestrictions() As DbSet(Of tblRegisterRestriction)
    Public Overridable Property tblSpisies() As DbSet(Of tblSpisy)
    Public Overridable Property tblSpisyDocuments() As DbSet(Of tblSpisyDocument)
    Public Overridable Property tblSpisyDohodies() As DbSet(Of tblSpisyDohody)
    Public Overridable Property tblSpisyFinanceInfoes() As DbSet(Of tblSpisyFinanceInfo)
    Public Overridable Property tblSpisyHistorieDohods() As DbSet(Of tblSpisyHistorieDohod)
    Public Overridable Property tblSpisyOsobies() As DbSet(Of tblSpisyOsoby)
    Public Overridable Property tblSpisyOsobyAdresies() As DbSet(Of tblSpisyOsobyAdresy)
    Public Overridable Property tblSpisyOsobyEmails() As DbSet(Of tblSpisyOsobyEmail)
    Public Overridable Property tblSpisyOsobyPhones() As DbSet(Of tblSpisyOsobyPhone)
    Public Overridable Property tblSpisyOsobyZams() As DbSet(Of tblSpisyOsobyZam)
    Public Overridable Property tblSpisyPlatbyDosles() As DbSet(Of tblSpisyPlatbyDosle)
    Public Overridable Property tblSpisyPrintInfoes() As DbSet(Of tblSpisyPrintInfo)
    Public Overridable Property tblSpisyPrintInfoCEZs() As DbSet(Of tblSpisyPrintInfoCEZ)
    Public Overridable Property tblSpisyRecordHistories() As DbSet(Of tblSpisyRecordHistory)
    Public Overridable Property tblSpisyTypOsobies() As DbSet(Of tblSpisyTypOsoby)
    Public Overridable Property tblTMPSpisyRecordHistories() As DbSet(Of tblTMPSpisyRecordHistory)

    Public Overridable Function sp_INT_Cash_AddFee_SKUZ() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_INT_Cash_AddFee_SKUZ")
    End Function

    Public Overridable Function sp_INT_FindAndPairPayments() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_INT_FindAndPairPayments")
    End Function

    Public Overridable Function sp_INT_NewAddresses(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewAddresses_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewAddresses_Result)("sp_INT_NewAddresses", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewDocuments(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewDocuments_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewDocuments_Result)("sp_INT_NewDocuments", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewEmails(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewEmails_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewEmails_Result)("sp_INT_NewEmails", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewEmployers(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewEmployers_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewEmployers_Result)("sp_INT_NewEmployers", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewPayments(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewPayments_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewPayments_Result)("sp_INT_NewPayments", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewPhones(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewPhones_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewPhones_Result)("sp_INT_NewPhones", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_NewVisitReport(lastTStamp As Nullable(Of Long), newTStamp As Nullable(Of Long)) As ObjectResult(Of sp_INT_NewVisitReport_Result)
        Dim lastTStampParameter As ObjectParameter = If(lastTStamp.HasValue, New ObjectParameter("LastTStamp", lastTStamp), New ObjectParameter("LastTStamp", GetType(Long)))

        Dim newTStampParameter As ObjectParameter = If(newTStamp.HasValue, New ObjectParameter("NewTStamp", newTStamp), New ObjectParameter("NewTStamp", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_INT_NewVisitReport_Result)("sp_INT_NewVisitReport", lastTStampParameter, newTStampParameter)
    End Function

    Public Overridable Function sp_INT_O2S_tblSpisyRecordHistory() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_INT_O2S_tblSpisyRecordHistory")
    End Function

    Public Overridable Function sp_INT_Truncate_tblTMPSpisyRecordHistory() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_INT_Truncate_tblTMPSpisyRecordHistory")
    End Function

    Public Overridable Function sp_Get_Region(pSC As String, region As ObjectParameter) As Integer
        Dim pSCParameter As ObjectParameter = If(pSC IsNot Nothing, New ObjectParameter("PSC", pSC), New ObjectParameter("PSC", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Get_Region", pSCParameter, region)
    End Function

    Public Overridable Function sp_Run_AfterSyncInterface() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Run_AfterSyncInterface")
    End Function

    Public Overridable Function sp_Get_LastTimeStamp(newIDSync As ObjectParameter, lastTStamp As ObjectParameter, newTStamp As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Get_LastTimeStamp", newIDSync, lastTStamp, newTStamp)
    End Function

    Public Overridable Function sp_Do_FinishSync(iDSync As Nullable(Of Long)) As Integer
        Dim iDSyncParameter As ObjectParameter = If(iDSync.HasValue, New ObjectParameter("IDSync", iDSync), New ObjectParameter("IDSync", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Do_FinishSync", iDSyncParameter)
    End Function

    Public Overridable Function sp_Do_VisitReportUpdateJournal(iDVisitReport As Nullable(Of Integer), rr_Journal As Nullable(Of Byte)) As Integer
        Dim iDVisitReportParameter As ObjectParameter = If(iDVisitReport.HasValue, New ObjectParameter("IDVisitReport", iDVisitReport), New ObjectParameter("IDVisitReport", GetType(Integer)))

        Dim rr_JournalParameter As ObjectParameter = If(rr_Journal.HasValue, New ObjectParameter("rr_Journal", rr_Journal), New ObjectParameter("rr_Journal", GetType(Byte)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Do_VisitReportUpdateJournal", iDVisitReportParameter, rr_JournalParameter)
    End Function

End Class
