'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OracleEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OracleEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AGCZ_CE_DOCUMENTS_TBL() As DbSet(Of AGCZ_CE_DOCUMENTS_TBL)
    Public Overridable Property AGCZ_PAYMENTS_TBL() As DbSet(Of AGCZ_PAYMENTS_TBL)
    Public Overridable Property AGCZ_SUBS_ADDRESSES_TBL() As DbSet(Of AGCZ_SUBS_ADDRESSES_TBL)
    Public Overridable Property AGCZ_SUBS_CONTACTS_EML_TBL() As DbSet(Of AGCZ_SUBS_CONTACTS_EML_TBL)
    Public Overridable Property AGCZ_SUBS_CONTACTS_EMP_TBL() As DbSet(Of AGCZ_SUBS_CONTACTS_EMP_TBL)
    Public Overridable Property AGCZ_SUBS_PHONES_TBL() As DbSet(Of AGCZ_SUBS_PHONES_TBL)
    Public Overridable Property AGCZ_VISIT_REPORT_TBL() As DbSet(Of AGCZ_VISIT_REPORT_TBL)
    Public Overridable Property CZ_FIELD_VISIT_OUT() As DbSet(Of CZ_FIELD_VISIT_OUT)
    Public Overridable Property AGCZ_REGISTER_RESTRICTIONS_TBL() As DbSet(Of AGCZ_REGISTER_RESTRICTIONS_TBL)
    Public Overridable Property CZ_ACC_SUBS_INT_VW() As DbSet(Of CZ_ACC_SUBS_INT_VW)
    Public Overridable Property CZ_ACCOUNT_DEBTS_VW() As DbSet(Of CZ_ACCOUNT_DEBTS_VW)
    Public Overridable Property CZ_ACCOUNT_INFO_VW() As DbSet(Of CZ_ACCOUNT_INFO_VW)
    Public Overridable Property CZ_ACCOUNT_INFO_XML_VW() As DbSet(Of CZ_ACCOUNT_INFO_XML_VW)
    Public Overridable Property CZ_ACCOUNTS_VW() As DbSet(Of CZ_ACCOUNTS_VW)
    Public Overridable Property CZ_CE_DOCUMENTS_VW() As DbSet(Of CZ_CE_DOCUMENTS_VW)
    Public Overridable Property CZ_CLIENTS_VW() As DbSet(Of CZ_CLIENTS_VW)
    Public Overridable Property CZ_COLLENT_COMMENTS_VW() As DbSet(Of CZ_COLLENT_COMMENTS_VW)
    Public Overridable Property CZ_KOLLECTO_PARAMETERS_VW() As DbSet(Of CZ_KOLLECTO_PARAMETERS_VW)
    Public Overridable Property CZ_PA_INSTALLMENT_HISTORY_VW() As DbSet(Of CZ_PA_INSTALLMENT_HISTORY_VW)
    Public Overridable Property CZ_PA_INSTALLMENTS_VW() As DbSet(Of CZ_PA_INSTALLMENTS_VW)
    Public Overridable Property CZ_PAYMENTS_VW() As DbSet(Of CZ_PAYMENTS_VW)
    Public Overridable Property CZ_PRINT_ADD_INFO_CEZ_VW() As DbSet(Of CZ_PRINT_ADD_INFO_CEZ_VW)
    Public Overridable Property CZ_PRINT_ADD_INFO_VW() As DbSet(Of CZ_PRINT_ADD_INFO_VW)
    Public Overridable Property CZ_SUBSCRIBER_ADDRESSES_VW() As DbSet(Of CZ_SUBSCRIBER_ADDRESSES_VW)
    Public Overridable Property CZ_SUBSCRIBER_CONTACTS_EML_VW() As DbSet(Of CZ_SUBSCRIBER_CONTACTS_EML_VW)
    Public Overridable Property CZ_SUBSCRIBER_CONTACTS_EMP_VW() As DbSet(Of CZ_SUBSCRIBER_CONTACTS_EMP_VW)
    Public Overridable Property CZ_SUBSCRIBER_PHONES_VW() As DbSet(Of CZ_SUBSCRIBER_PHONES_VW)
    Public Overridable Property CZ_SUBSCRIBERS_VW() As DbSet(Of CZ_SUBSCRIBERS_VW)

End Class
