'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCreditor
    Public Property IDCreditor As Integer
    Public Property IDSrcCreditor As Nullable(Of Long)
    Public Property CreditorName As String
    Public Property CreditorAlias As String
    Public Property CreditorStreet As String
    Public Property CreditorHouseNum As String
    Public Property CreditorCity As String
    Public Property CreditorZipCode As String
    Public Property CreditorAddrFull As String
    Public Property LimitDaysFor1OSN As Nullable(Of Short)
    Public Property LimitDaysForNOSN As Nullable(Of Short)
    Public Property Processor As String
    Public Property TStamp As Byte()
    Public Property TemplateDLSpis As String
    Public Property TemplateDLSpisValid As Boolean
    Public Property TemplateFVLetter As String
    Public Property TemplateFVLetterValid As Boolean
    Public Property TemplateUZSK As String
    Public Property TemplateUZSKValid As Boolean

    Public Overridable Property tblSpisies As ICollection(Of tblSpisy) = New HashSet(Of tblSpisy)

End Class
