'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblOtherInfo
    Public Property IDOtherInfo As Integer
    Public Property IDSpisu As Integer
    Public Property OtherInfoXML As String
    Public Property TStamp As Byte()

    Public Overridable Property tblSpisy As tblSpisy

End Class
