'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyPrintInfoCEZ
    Public Property IDSpisyPrintInfoCEZ As Integer
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property CEZ_IDSrcACC As String
    Public Property CEZ_SuplyPlace As String
    Public Property CEZ_VariableSymbol As String
    Public Property CEZ_DueDate As Nullable(Of Date)
    Public Property CEZ_AmountTotal As Nullable(Of Decimal)
    Public Property CEZ_AmountSupplement As Nullable(Of Decimal)
    Public Property TStamp As Byte()

End Class
