'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyTypOsoby
    Public Property IDSpisu As Integer
    Public Property IDSpisyOsoby As Integer
    Public Property rr_PersType As Short
    Public Property PersMain As Boolean
    Public Property DateSignSKUZ As Nullable(Of Date)
    Public Property TStamp As Byte()

    Public Overridable Property tblSpisy As tblSpisy
    Public Overridable Property tblSpisyOsoby As tblSpisyOsoby

End Class
