'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyPrintInfo
    Public Property IDSpisyPrintInfo As Integer
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property IDSrcACC As String
    Public Property CustomerID As String
    Public Property CustomerID2 As String
    Public Property RegisterInfo As String
    Public Property ACC_Comment9 As String
    Public Property ACC_comment13 As String
    Public Property ACC_comment14 As String
    Public Property ACC_comment17 As String
    Public Property ACC_Comment23 As String
    Public Property ACC_comment27 As String
    Public Property PF_Agreement As String
    Public Property AmountByWords As String
    Public Property AmountByWordsHal As String

End Class
