'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyOsobyZam
    Public Property IDSpisyOsobyZam As Integer
    Public Property IDSpisyOsoby As Integer
    Public Property IDSrcSpisyOsobyZam As Nullable(Of Long)
    Public Property EmployerName As String
    Public Property EmployerIC As String
    Public Property EmployerCity As String
    Public Property EmployerHouseNum As String
    Public Property EmployerStreet As String
    Public Property EmployerZipCode As String
    Public Property EmployerType As String
    Public Property rr_AddressValidity As Short
    Public Property EmployerAddrFull As String
    Public Property EmployerContactSurname As String
    Public Property EmployerContactName As String
    Public Property EmployerContactEmail As String
    Public Property EmployerContactPhone As String
    Public Property TStamp As Byte()
    Public Property rr_Journal As Byte
    Public Property TimeCreated As Date
    Public Property TimeValidityUpdate As Date

    Public Overridable Property tblSpisyOsoby As tblSpisyOsoby

End Class
