'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyOsobyPhone
    Public Property IDSpisyOsobyPhone As Integer
    Public Property IDSpisyOsoby As Integer
    Public Property IDSrcSpisyOsobyPhone As Nullable(Of Long)
    Public Property PersPhone As String
    Public Property rr_PhoneValidity As Short
    Public Property PersPhoneMain As Boolean
    Public Property PhoneFVisitComment As String
    Public Property TStamp As Byte()
    Public Property rr_Journal As Byte
    Public Property TimeValidityUpdate As Date
    Public Property TimeCreated As Date

    Public Overridable Property tblSpisyOsoby As tblSpisyOsoby

End Class
