'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyRecordHistory
    Public Property IDSpisyRecordHistory As Integer
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property RecordDate As Date
    Public Property RecordCommentType As String
    Public Property RecordCommentTxt As String
    Public Property RecordDocuDate As Nullable(Of Date)
    Public Property RecordDocuType As String
    Public Property RecordSended As Byte
    Public Property IDSrcSpisyRecordHistory As Nullable(Of Long)
    Public Property IDSrcSpisyRecordHistory2 As Nullable(Of Long)
    Public Property TStamp As Byte()

    Public Overridable Property tblSpisy As tblSpisy

End Class
