'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyFinanceInfo
    Public Property IDInfo As Integer
    Public Property IDSrcInfo As Nullable(Of Long)
    Public Property IDSpisu As Integer
    Public Property InfoTxt As String
    Public Property InfoKind As String
    Public Property InfoInvoice As String
    Public Property InfoAmount As Nullable(Of Double)
    Public Property InfoAmountBalance As Nullable(Of Double)
    Public Property InfoAmountBalanceUpdated As Nullable(Of Double)
    Public Property InfoDate As Nullable(Of Date)
    Public Property InfoDueDate As Nullable(Of Date)
    Public Property InfoCurrency As String
    Public Property TStamp As Byte()

    Public Overridable Property tblSpisy As tblSpisy

End Class
