'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyHistorieDohod
    Public Property IDSpisyHistorieDohod As Integer
    Public Property IDSpisu As Integer
    Public Property IDSrcSpisyHistorieDohod As Nullable(Of Long)
    Public Property DateSK As Nullable(Of Date)
    Public Property Amount As Nullable(Of Double)
    Public Property CountOfPaymentsSK As Nullable(Of Short)
    Public Property rr_PAValidityType As Nullable(Of Short)
    Public Property rr_PAType As Nullable(Of Short)
    Public Property PAInvalid As Boolean
    Public Property TStamp As Byte()

    Public Overridable Property tblSpisy As tblSpisy

End Class
