'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSpisyPlatbyDosle
    Public Property IDSpisyPlatbyDosle As Integer
    Public Property IDSpisu As Integer
    Public Property IDSrcSpisyPlatbyDosle As Nullable(Of Long)
    Public Property PaymentDate As Nullable(Of Date)
    Public Property Amount As Nullable(Of Double)
    Public Property CommissionForIP As Nullable(Of Double)
    Public Property rr_PaymentLabel As Byte
    Public Property OverPayment As Nullable(Of Double)
    Public Property Paired As Boolean
    Public Property TStamp As Byte()
    Public Property rr_Charged As Byte

    Public Overridable Property tblSpisy As tblSpisy

End Class
