'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTMPSpisyRecordHistory
    Public Property COLLENT_COMMENT_ID As Integer
    Public Property ACCOUNT_ID As Integer
    Public Property CREATION_DATE As Nullable(Of Date)
    Public Property COMMENT_TYPE_NAME As String
    Public Property USER_COMMENT As String
    Public Property IDSpisu As Nullable(Of Integer)
    Public Property IDSpisyRecordHistory As Nullable(Of Integer)

End Class
